apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      initContainers:
        - name: ensure-vault-token
          env:
            - name: VAULT_ADDR
              value: '{{ .Values.vaultAddr }}'
            - name: VAULT_ROLE
              value: '{{ .Values.vaultRole }}'
      containers:
        - name: manager
          args:
            - --config=/var/run/controller-manager-cm/config.yaml
            - --config=/var/run/controller-manager-secret/secret.yaml
          volumeMounts:
            - name: controller-manager-cm
              mountPath: /var/run/controller-manager-cm/config.yaml
              readOnly: true
            - name: controller-manager-secret
              mountPath: /var/run/controller-manager-secret/secret.yaml
              readOnly: true
      volumes:
        - name: controller-manager-cm
          configMap:
            name: controller-manager
        - name: controller-manager-secret
          secret:
            secretName: controller-manager
