apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-manager
  namespace: system
data:
  config.yaml: |
    leader-elect: {{ .Values.leaderElect }}
    metrics-bind-address: {{ .Values.metricsBindAddress | quote }}
    provider: {{ .Values.provider | quote }}
    vault-addr: {{ .Values.vaultAddr | quote }}
