apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      initContainers:
      - name: ensure-vault-token
        env:
        - name: VAULT_ADDR
          value: '{{ .Values.vaultAddr }}'
        - name: VAULT_ROLE
          value: '{{ .Values.vaultRole }}'
      containers:
      - name: manager
        envFrom:
        - configMapRef:
            name: controller-manager
        - secretRef:
            name: controller-manager
