apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: '{{ .Release.Name }}'
    meta.helm.sh/release-namespace: '{{ .Release.Namespace }}'
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}'
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    meta.helm.sh/release-name: '{{ .Release.Name }}'
    meta.helm.sh/release-namespace: '{{ .Release.Namespace }}'
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}'
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager-psp'
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  hostIPC: false
  hostNetwork: false
  hostPID: false
  privileged: false
  runAsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - secret
  - configMap
  - hostPath
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    meta.helm.sh/release-name: '{{ .Release.Name }}'
    meta.helm.sh/release-namespace: '{{ .Release.Namespace }}'
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}'
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-leader-election-role'
  namespace: '{{ .Release.Namespace }}'
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: '{{ .Release.Name }}'
    meta.helm.sh/release-namespace: '{{ .Release.Namespace }}'
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}'
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager-psp'
rules:
- apiGroups:
  - extensions
  resourceNames:
  - '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager-psp'
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: '{{ .Release.Name }}'
    meta.helm.sh/release-namespace: '{{ .Release.Namespace }}'
  creationTimestamp: null
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}'
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-manager-role'
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.x-k8s.io.giantswarm.io
  resources:
  - clusters/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: '{{ .Release.Name }}'
    meta.helm.sh/release-namespace: '{{ .Release.Namespace }}'
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}'
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-leader-election-rolebinding'
  namespace: '{{ .Release.Namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-leader-election-role'
subjects:
- kind: ServiceAccount
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: '{{ .Release.Name }}'
    meta.helm.sh/release-namespace: '{{ .Release.Namespace }}'
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}'
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager-psp'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager-psp'
subjects:
- kind: ServiceAccount
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: '{{ .Release.Name }}'
    meta.helm.sh/release-namespace: '{{ .Release.Namespace }}'
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}'
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-manager-rolebinding'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: v1
data:
  config.yaml: |
    leader-elect: {{ .Values.leaderElect }}
    metrics-bind-address: {{ .Values.metricsBindAddress | quote }}
    provider: {{ .Values.provider | quote }}
    vault-addr: {{ .Values.vaultAddr | quote }}
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: '{{ .Release.Name }}'
    meta.helm.sh/release-namespace: '{{ .Release.Namespace }}'
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}'
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: '{{ .Release.Name }}'
    meta.helm.sh/release-namespace: '{{ .Release.Namespace }}'
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    helm.sh/chart: '{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}'
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
stringData:
  secret.yaml: ""
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: '{{ .Release.Name }}'
    meta.helm.sh/release-namespace: '{{ .Release.Namespace }}'
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    control-plane: controller-manager
    helm.sh/chart: '{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}'
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager-vault-token'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: '{{ .Release.Name }}'
    meta.helm.sh/release-namespace: '{{ .Release.Namespace }}'
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name | trunc 63 | trimSuffix "-" }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    control-plane: controller-manager
    helm.sh/chart: '{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}'
  name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app.giantswarm.io/branch: '{{ .Values.project.branch }}'
      app.giantswarm.io/commit: '{{ .Values.project.commit }}'
      app.kubernetes.io/instance: '{{ .Release.Name }}'
      app.kubernetes.io/managed-by: '{{ .Release.Service }}'
      app.kubernetes.io/name: '{{ .Chart.Name | trunc 63 | trimSuffix "-" }}'
      app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
      control-plane: controller-manager
      helm.sh/chart: '{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}'
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: '{{ .Release.Name }}'
        meta.helm.sh/release-namespace: '{{ .Release.Namespace }}'
      labels:
        app.giantswarm.io/branch: '{{ .Values.project.branch }}'
        app.giantswarm.io/commit: '{{ .Values.project.commit }}'
        app.kubernetes.io/instance: '{{ .Release.Name }}'
        app.kubernetes.io/managed-by: '{{ .Release.Service }}'
        app.kubernetes.io/name: '{{ .Chart.Name | trunc 63 | trimSuffix "-" }}'
        app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
        control-plane: controller-manager
        helm.sh/chart: '{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" -}}'
    spec:
      containers:
      - args:
        - --config=/var/run/controller-manager-cm/config.yaml
        - --config=/var/run/controller-manager-secret/secret.yaml
        command:
        - /manager
        env:
        - name: VAULT_TOKEN
          valueFrom:
            secretKeyRef:
              key: token
              name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager-vault-token'
        image: '{{ .Values.registry.domain }}/{{ .Values.image.name }}:{{ .Values.image.tag }}'
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /var/run/controller-manager-cm/config.yaml
          name: controller-manager-cm
          readOnly: true
        - mountPath: /var/run/controller-manager-secret/secret.yaml
          name: controller-manager-secret
          readOnly: true
        - mountPath: /etc/ssl/certs/
          name: ssl-certs
      initContainers:
      - args:
        - --vault-address=$(VAULT_ADDR)
        - --vault-role=$(VAULT_ROLE)
        - --vault-token-secret-name={{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager-vault-token
        - --vault-token-secret-namespace={{ .Release.Namespace }}
        env:
        - name: VAULT_ADDR
          value: '{{ .Values.vaultAddr }}'
        - name: VAULT_ROLE
          value: '{{ .Values.vaultRole }}'
        image: giantswarm/k8s-jwt-to-vault-token:0.1.0
        imagePullPolicy: Always
        name: ensure-vault-token
      securityContext:
        runAsGroup: 1000
        runAsUser: 1000
      serviceAccountName: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager'
      terminationGracePeriodSeconds: 10
      volumes:
      - configMap:
          name: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager'
        name: controller-manager-cm
      - name: controller-manager-secret
        secret:
          secretName: '{{- .Release.Name | replace "." "-" | trunc 33 | trimSuffix "-" -}}-controller-manager'
      - hostPath:
          path: /etc/ssl/certs/
        name: ssl-certs
