version: 2.1

orbs:
  architect: giantswarm/architect@2.11.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: capi-migration
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-capi-migration-to-quay
          image: "quay.io/giantswarm/capi-migration"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-capi-migration-to-aliyun
          image: "registry-intl.cn-shanghai.aliyuncs.com/giantswarm/capi-migration"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-capi-migration-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "capi-migration"
          requires:
            - push-capi-migration-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-capi-migration-to-aws-app-collection
          context: architect
          app_name: "capi-migration"
          app_namespace: "giantswarm"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-capi-migration-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-capi-migration-to-azure-app-collection
          context: architect
          app_name: "capi-migration"
          app_namespace: "giantswarm"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-capi-migration-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
