apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: giantswarm
namePrefix: capi-migration-dev-
nameSuffix: -changed-by-make-deploy

images:
- name: controller
  newName: giantswarm/capi-migration
  newTag: latest

resources:
- ../default

components:
- ../components/psp
- ../components/vault-access

patchesStrategicMerge:
# NOTE: manager_patch.yaml is intentionally ignored in .gitignore !!!
#       Check the manager_patch.example.yaml for inspiration.
- manager_patch.yaml
