apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: capi-migration-system-dev
namePrefix: capi-migration-

images:
- name: controller
  newName: giantswarm/capi-migration
  newTag: latest

resources:
- ../giantswarm
- namespace.yaml
