namespace: giantswarm

configurations:
- namereference.yaml

bases:
- ../default

resources:
- psp.yaml
- psp_role.yaml
- psp_role_binding.yaml

patchesStrategicMerge:
# This patch is required to set the user and group ID so it satisfies the PSP.
- manager_security_context_patch.yaml
