name: CI

on: [ "push" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.2'
      # This can be removed when switching to kubebuilder@v3.
      # For now etcd binary is required to be in there.
      - name: Install kubebuilder
        env:
          version: "2.3.2"
        run: |
          curl -L https://go.kubebuilder.io/dl/${{ env.version }}/linux/amd64 | tar -xz -C /tmp
          sudo mv /tmp/kubebuilder_${{ env.version }}_linux_amd64 /usr/local/kubebuilder
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          path: |
            ~/go/pkg/mod
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: make test
