name: CI

on: [ "push" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.2'
      # This can be removed when switching to kubebuilder@v3.
      - name: Install kubebuilder
        run: |
          sudo mkdir -p /usr/local/kubebuilder
          sudo chmod 0777 /usr/local/kubebuilder
          curl -L https://go.kubebuilder.io/dl/2.3.2/linux/amd64 | tar -xz -C /usr/local/kubebuilder
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          path: |
            ~/go/pkg/mod
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: make test
